### ISSUE TITLE
Card error Cannot destructure property `show` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by mrneilix** [PiotrMachowski/lovelace-google-keep-card#1]
I keep seeing this in the card: Cannot destructure property `show` of 'undefined' or 'null'.

My config is:

```
  - type: custom:google-keep-card
    template: google_keep_card_template
    entity: sensor.keep_xxx
    show:
      - unchecked
      - checked
```
