### ISSUE TITLE
Card Not Showing

### ISSUE THREAD

**Issue by gregcsw** [PiotrMachowski/lovelace-google-keep-card#5]
Hi Piotr

Thank you for this card.

It was working perfectly for a few days and now the card doesn't show in lovelace.

```
          - type: custom:google-keep-card
            entity: sensor.google_keep_c6fe53a582
            show:
              - unchecked

```
If I change the config to include an error I get the red box, but with the correct config I get nothing.

I have tried adding and removing all config options and still no luck. 

I check the state of the sensor and the list items are showing in state.

Any guidance is appreciated. Thank you
