### ISSUE TITLE
Card not showing before reload, then lacks checkboxes

### ISSUE THREAD

**Issue by pjaspinski** [PiotrMachowski/lovelace-google-keep-card#9]
Hi,
First of all, thank you for creating this card, I really enjoy using it.
~~When I load my HA the card is not showing, there is a space for it, but the card is not there. It appears as soon as I reload the site.~~
Second issue is that after reload it does not show checkboxes on the left side, even though the note is a checked list in Keep . It looks like this:
![Zrzut ekranu 2020-10-30 105036](https://user-images.githubusercontent.com/59670068/97690798-c14a6d00-1a9d-11eb-8992-9bc324251c2d.png)
Card config:
```yaml
type: 'custom:google-keep-card'
entity: sensor.google_keep_xxxxxxxxxx
theme: dark
alpha: 0.8
show:
  - unchecked
```
Hope you can help with these!
